import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next.js on every build and its triple-slash
    // references are not ours to change.
    ignores: [
      "legacy/**",
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      "prisma/generated/**",
    ],
  },
];

export default eslintConfig;
